language: ruby

before_install:
  - sudo apt-get update
  - sudo apt-get install libimage-exiftool-perl imagemagick
  - exiftool -ver

rvm:
  - 2.3

env:
- ASSETHOST_HOST_PROTOCOL=http
- SH=bash
- PACKAGE_VERSION="1.0.*"