language: ruby

before_install:
  - sudo apt-get update
  - sudo apt-get install libimage-exiftool-perl imagemagick
  - exiftool -ver

install:
  - bundle install --path vendor/bundle

before_script:
  - cp config/templates/.env.template .env.test
#   - cp config/templates/secrets.yml.template config/secrets.yml

script: 
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/

services:
  - mongodb
  - redis-server

cache: bundler

rvm:
  - 2.3

env:
  - SH=bash
  - PACKAGE_VERSION="1.0.*"




