language: ruby

before_install:
  - sudo apt-get update
  - sudo apt-get install libimage-exiftool-perl imagemagick
  - exiftool -ver

install:
  - bundle install --path vendor/bundle

services:
  - mysql

rvm:
  - 2.3

env:
  - ASSETHOST_HOST_PROTOCOL=http
  - SH=bash
  - PACKAGE_VERSION="1.0.*"