version: '3'

services:

  assethost: &main
    image: scprdev/assethost
    container_name: assethost
    ports:
      - 8080:8080/tcp
    env_file:
      - .env.development.docker
    stdin_open: true
    tty: true
    networks:
      assethost-network:
        aliases:
          - assethost
    depends_on:
      - mongodb
      - mysql
      - elasticsearch
      - redis
      - s3
  
  worker:
    <<: *main
    container_name: worker
    command: worker
    networks:
      assethost-network:
        aliases:
          - worker
    ports: []
    depends_on:
      - assethost

  mongodb:
    image: bitnami/mongodb:3.6.4
    networks:
      assethost-network:
        aliases:
          - mongodb
    ports:
      - 27017:27017/tcp
    volumes:
      - mongodb-data:/bitnami

  mysql: &defaults
    image: mysql:5.7.21
    container_name: assethost-mysql
    ports:
      - 3200:3200/tcp
      - 3306:3306/tcp
    restart: always
    command: $DEPLOYBOT_TOKEN
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      assethost-network:
        aliases:
         - mysql

  redis:
    image: redis:4.0.1-alpine
    container_name: assethost-redis
    ports:
      - 6379:6379/tcp
    networks:
      assethost-network:
        aliases:
         - redis

  elasticsearch:
    image: elasticsearch:1.7-alpine
    container_name: assethost-elasticsearch
    ports:
      - 9200:9200/tcp
      - 9300:9300/tcp
    volumes:
      - elasticsearch-data:/var/lib/elasticsearch
    networks:
      assethost-network:
        aliases:
         - elasticsearch

  s3:
    image: fingershock/fakes3:0.2.4
    container_name: assethost-s3
    ports:
      - 8000:8000/tcp
    volumes:
      - s3-data:/fakes3_data:rw
    networks:
      assethost-network:
        aliases:
          - s3

volumes:
  mongodb-data:
  mysql-data:
  elasticsearch-data:
  s3-data:

networks:
  assethost-network:

