version: '3'

services:

  # ruby: &main
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.development
  #   container_name: ruby
  #   ports:
  #     - 2015:2015/tcp
  #   environment:
  #     - RAILS_ENV=development
  #     - ASSETHOST_IS_DOCKER=true
  #   working_dir: /home/assethost
  #   stdin_open: true
  #   tty: true
  #   networks:
  #     assethost-network:
  #       aliases:
  #         - ruby
  #   volumes:
  #     - ./:/home/assethost
  #     - ruby-bundle:/usr/local/bundle
  #     - ruby-gems:/usr/local/lib/ruby/gems/
  #     - ruby-node-modules:/home/assethost/frontend/node_modules/
  #   depends_on:
  #     - mongodb
  #     - elasticsearch
  #     - redis
  #     - s3


  # worker:
  #   <<: *main
  #   container_name: worker
  #   command: worker
  #   restart: always
  #   networks:
  #     assethost-network:
  #       aliases:
  #         - worker
  #   ports: []
  #   depends_on:
  #     - ruby
  #   volumes: []
  #   volumes_from:
  #     - ruby


  mongodb:
    image: bitnami/mongodb:3.6.4
    container_name: assethost-mongodb
    networks:
      assethost-network:
        aliases:
          - mongodb
    ports:
      - 27017:27017/tcp
    volumes:
      - mongodb-data:/bitnami


  redis:
    image: redis:4.0.1-alpine
    container_name: assethost-redis
    ports:
      - 6379:6379/tcp
    networks:
      assethost-network:
        aliases:
         - redis


  elasticsearch:
    image: elasticsearch:1.7-alpine
    container_name: assethost-elasticsearch
    ports:
      - 9200:9200/tcp
      - 9300:9300/tcp
    volumes:
      - elasticsearch-data:/var/lib/elasticsearch
    networks:
      assethost-network:
        aliases:
         - elasticsearch


  s3:
    image: fingershock/fakes3:0.2.4
    container_name: assethost-s3
    ports:
      - 8000:8000/tcp
    volumes:
      - s3-data:/fakes3_data:rw
    networks:
      assethost-network:
        aliases:
          - s3


volumes:
  ruby-bundle:
  ruby-gems:
  ruby-node-modules:
  mongodb-data:
  elasticsearch-data:
  s3-data:
  # nfsmount:
  #   driver: local
  #   driver_opts:
  #     type: nfs
  #     o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
  #     device: ":."


networks:
  assethost-network:

